/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.Scanner;

import org.example.Exercicios.ExercicioDois.AppDesenho2D;
import org.example.Exercicios.ExercicioUm.Jogo;

public class App {
    public static void main(String[] args) {
        try (Scanner input = new Scanner(System.in)) {
            System.out.print("Escolha qual exercício executar: \n1- Java of Empires \n2 - Desenho vetorial 2D \n> ");
            int escolha = input.nextInt();
            switch (escolha) {
                case 1 -> Jogo.main(args);
                case 2 -> AppDesenho2D.main(args);
                default -> {
                    System.out.println("Opção inválida");
                    throw new AssertionError();
                }
            }
        }
    }
}
